# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Blog for Frances
email: frances.swiecki@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In which our protagonist blogs about all of the new things she is learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: -none yet-
github_username:  fswiecki

# Build settings
markdown: kramdown
